### PR TITLE
Update package.json to include ghost 0.11.3

### PR DESCRIPTION
**Pull request by Waterloo**

### CODE REVIEW

**Comment by cobyism** [comment]
🙇 ⚡️ ❤️  @Waterloo Thanks for this!

*Note: also bumped casper to the latest release (1.3.4) too.*

**Comment by kevin-stripe** [comment]
@cobyism heads up that this version requires a node bump as well.

**Comment by holic** [comment]
@cobyism heads up that this version requires a node bump as well (see my comment here #85).

**Comment by cobyism** [comment]
> @cobyism heads up that this version requires a node bump as well (see my comment here #85).

Ugh, my bad entirely. I even remember reading that comment too 😣. I’m going to go ahead and revert this merge so shit isn’t broken. @Waterloo Thanks again for the PR, even though we’re going to revert 👍

**Pull request merged**
