### PR TITLE
use add-on after deployment

### PR DESCRIPTION
**Pull request by csquared**
in this PR we don't add the add-on in the app template, but we still make it easy for people to use should they so choose to use it.

the readme is explicit about the options and the cost.

### CODE REVIEW

**Comment by csquared** [comment]
wish i could just make doc changes, but we still need that little bit in config.js to pick up the env when its there.

that's pretty standard and makes it easy for someone to clone the project, get it running, then add the add-on later instead of futzing with the AWS console.

**Comment by cobyism** [comment]
I’m open to having something in the `config.js` to catch this if the bucketeer environment variables are present. With the docs though, I’m concerned that putting this above the manual configuration will confuse people, because this section of the docs is all under the "What do I put in the deployment and environment variable fields?" header, and at that point in a person’s deployment journey (filling out the herokuy deployment form), they *by definition* don’t have a heroku app yet against which they can run `heroku addons:create …`.

As an alternative, what if the docs flow went something like this:

```md
##### Configuring an S3 bucket manually

[…]

##### Provisioning an S3 bucket using an add-on

If you’d prefer not to configure S3 manually, you can provision the [Bucketeer add-on](https://devcenter.heroku.com/articles/bucketeer)
to get an S3 bucket (Bucketeer starts at $5/mo).

To configure S3 via Bucketeer, leave all the S3 deployment fields blank and deploy your
Ghost blog. Once your blog is deployed, run the following commands from your terminal:

    heroku addons:create bucketeer --app YOURAPPNAME

The environment variables set by the add-on will be automatically detected and used to
configure your Ghost blog and enable uploads.
```

Would that be a more accurate explanation of the steps people would go through?

**Comment by csquared** [comment]
@cobyism that makes sense and the wording is great. :+1:

**Comment by holic** [comment]
Overwriting `process.env` variables seems like it might be asking for trouble (see global variables). What about an additional condition to set up the `storage` variable like we do for `S3_...` values?

**Comment by csquared** [comment]
moved to a new PR: https://github.com/cobyism/ghost-on-heroku/pull/50

**Pull request closed without merging**
