### PR TITLE
Upgrade to Ghost 0.6.4 and Casper 1.2.4

### PR DESCRIPTION
**Pull request by holic**

### CODE REVIEW

**Comment by cobyism** [comment]
@holic :heart: Thanks for the pull request! Any chance you could pull in the latest Casper theme too (e.g. as other people have previously done in https://github.com/cobyism/ghost-on-heroku/pull/8 and https://github.com/cobyism/ghost-on-heroku/pull/6)?

**Comment by holic** [comment]
Yup - done!

**Comment by cobyism** [comment]
Awesome, thanks! Just one question: the [latest release](https://github.com/TryGhost/Casper/releases) of Casper seems to be 1.2.3. Have they released a 1.2.4 somewhere else?

**Comment by holic** [comment]
Ah, I just grabbed the latest from the repo: https://github.com/TryGhost/Casper/commits/master

Should I just use the latest release instead?

**Comment by cobyism** [comment]
There could still be more changes on `master` before they release 1.2.4, so yeah I’d prefer to keep it to just the last official release of the Casper theme instead. :+1:

**Comment by holic** [comment]
@cobyism All done! Also pinged @ErisDS about the 1.2.4 release: https://twitter.com/kingersoll/status/621012089243598848

**Comment by holic** [comment]
Latest is now 1.2.4. I've bumped it in my PR.

**Comment by holic** [comment]
There's an interesting issue now. `1.2.4` was tagged a few commits after the version of Casper that's included with Ghost. Would you prefer to use the exact commit that was included with Ghost or the tagged release from the Casper repo?

**Comment by ErisDS** [comment]
> There's an interesting issue now. 1.2.4 was tagged a few commits after the version of Casper that's included with Ghost

This is something I need to fix.

**Comment by ErisDS** [comment]
Done :+1:

**Comment by holic** [comment]
Thanks @ErisDS!

**Comment by cobyism** [comment]
@holic @ErisDS :sparkling_heart: :zap: :+1: Awesome. Thanks!

**Pull request merged**
