### PR TITLE
Use bucketeer for s3

### PR DESCRIPTION
**Pull request by csquared**
This PR detects when the configuration for the Heroku add-on bucketeer is available and uses that config. I have to specify my branch of `ghost-s3` to enable the bucket prefix on the free plan. You can track progress on that merge here: https://github.com/muzix/ghost-s3/pull/15.  Turns out someone else had a similar issue and commit here: https://github.com/muzix/ghost-s3/pull/9/files.  

When either of those get merged in you can stop using `c2industries/ghost-s3`. I'll happily maintain my fork until those land.

Bucketeer will go GA next Monday, so have some time to incorporate feedback. Hold off on merging until then :)

Here's a screenshot of working file uploads on the free plan:

screen shot 2015-12-08 at 2 02 50 pm

It's backwards compatible with the old way of setting the config, but I've removed that from the README to make it simpler.

(Full disclosure, I run Bucketeer. who better to make this commit? :)

### CODE REVIEW

**Comment by csquared** [comment]
Updated the way I'm doing the config -> all Bucketeer add-ons get their own S3 bucket so I don't need the prefix functionality

**Comment by cobyism** [comment]
Having never heard of, nor used bucketeer before, can you please briefly explain how it fits into things, and why it should be part of the default set of things this repo provides? If someone takes this repo and looks to deploy it outside of Heroku (but in a Heroku-*like* environment, like Dokku or similar), will this degrade nicely? I’m definitely open to improvements to the S3 config management, but just want to make sure any extra dependency added to this project isn’t going to surprise people (who may not know how to *un*-configure something like this) in a weird way.

**Comment by csquared** [comment]
Sure. Buckeeter is an (in GA as of yesterday) Herkoku add-on that provides S3 buckets to Heroku apps. 

So instead of having to go provision S3 yourself, I've updated the `app.json` to include the add-on. That should make the whole thing work out of the box.

As far as the config changes, the net result *should be* only additive. It looks to see if the AWS credentials that Bucketeer sets (the familiar access key, secret, and bucket name) are available and uses those for image uploads. If not it falls back to the previous behavior.  If you don't want to do image uploads or use the addon, just doing `heroku addons:destroy bucketeer` should take care of it.

Lemme know what you think and if that's clear. I used the fact that heroku-postgresql and mailgun were already there as prior art, so a TL;DR version is I'm trying to do for S3 what those addons do for their respective services :)

**Comment by csquared** [comment]
To be a bit more clear on the env. You can use either bucketeer or set them yourself. The way I have it coded is that if both are set (ie you've configured it by hand *and* have the add-on added), the add-on wins but can update that :)

**Comment by cobyism** [comment]
:+1: Thanks for the clarifications, @csquared. I went to test this branch out myself, and I only just now realised this add-on is paid ($5/mo minimum). I appreciate the PR, however I’d like to keep the default version of this project free from anything requiring payment. There’s no way for people to deselect this add-on before deploying, and I think seeing a price would prevent a lot of people from trying out this project. For that reason, I’d rather people opt-in to add-ons requiring payment *after* deployment.

**Pull request closed without merging**
