### PR TITLE
Updated Ghost to 0.11.8

### PR DESCRIPTION
**Pull request by blaze33**
Just updated some dependencies to the latest stable version.  
Also upgraded node to v6 (the LTS one).

### CODE REVIEW

**Comment by cobyism** [comment]
Thanks for the pull request, @blaze33. I’m going to close a few other PRs people opened for earlier updates (which I unfortunately have been to preoccupied to get to), and concentrate on using this PR to bring everything up to date.

The only thing I’m not 100% on here is what we should set as the node version. Part of me feels like we should ensure it’s set to be [the same as Ghost itself](https://github.com/TryGhost/Ghost/blob/0.11.8/package.json#L26) (i.e. `^4.2.0 || ^6.9.0`). Thoughts?

@holic Do you have any lingering concerns about the memory issues people reported a while back with different Node versions on Heroku?

**Comment by blaze33** [comment]
Indeed there's a recommanded node version on Ghost itself. Personally I'm running with Node 6.10.3 without issue at [blog.openbloc.fr](http://blog.openbloc.fr). I just assumed that Ghost being regularly maintained it would work out of the box with the latest node LTS version.

Also I'm not sure what would heroku do with the `^4.2.0 || ^6.9.0`, which one does it choose ?

**Comment by holic** [comment]
> Do you have any lingering concerns about the memory issues people
reported a while back with different Node versions on Heroku?

No concerns from me!

**Comment by blaze33** [comment]
See #107 for the proper pull request, sorry ^^

**Pull request closed without merging**
