### PR TITLE
Upgrade to Ghost 0.7

### PR DESCRIPTION
**Pull request by Waterloo**
Ghost 0.7 comes with updated Admin dashboard and many other features and bug fixes under the hood

### CODE REVIEW

**Comment by holic** [comment]
0.7 also includes an upgrade to Casper theme 1.2.5. Can you include this in your PR please?

**Comment by cobyism** [comment]
We should really write a script or something that anyone can run to create a PR-ready diff for both Ghost and Casper, whenever they notice an update has been released.

**Comment by holic** [comment]
@cobyism Thoughts on requiring Casper as an npm dependency, then using a `postinstall` script to copy the contents to `content/themes/casper`? This would keep the source out of this repo and allow us to pin to specific versions via `package.json`.

**Comment by cobyism** [comment]
@holic If there’s a way to do that that’ll work predictably on Heroku, that’d be :metal:.

**Comment by holic** [comment]
Done in https://github.com/cobyism/ghost-on-heroku/pull/35 and https://github.com/cobyism/ghost-on-heroku/pull/36

**Pull request closed without merging**
